package de.hannesniederhausen.storynotes.export.internal.ui;
/**
 * 
 */

/**
 * 
 * Documentation Types which can be generated by the export.
 * 
 * @author Hannes Niederhausen
 *
 */
public enum DocType {
	HTML
}
